### ISSUE TITLE
Пара вопросов по работе паттерна

### ISSUE THREAD

**Issue by remenkoff** [AndreyPanov/ApplicationCoordinator#13]
Андрей, приветствую!

Посмотрел Вашу версию реализации данного паттерна, все очень здорово, спасибо!

Однако, у меня есть 2 вопроса:
1) Почему за состояние авторизации пользователя в приложении отвечает `ItemsListController`? (собственно, свойство `authCheck`). Более того, переход к модулю авторизации происходит в переопределенном методе `viewDidAppear` (т.е. показали список айтемов на миллисеекунду, потом поняли, что "нет, чувак, ты не авторизован", и дернули **опциональный** метод `authNeed`). 
Я понимаю, что это пример, но все же (по моему скромному мнению) именно координатор отвечает за состояние приложения, причем конкретно за авторизацию - ApplicationCoordinator.

2) Утечки памяти. Собственно, на днях, в очередной раз рассматривая различные реализации сего паттерна, отметил для себя удивительную вещь: паттерн неимоверно увеличивает риск утечек памяти. В каждой реализации я видел утечки. Собственно, и у Вас тоже :) Пруф:

<img width="304" alt="2017-03-03 22 58 13" src="https://cloud.githubusercontent.com/assets/3461969/23566900/eee47f28-0064-11e7-9dea-19cf3e0555d2.png">

Последовательность была такая: `Auth -> SignUp -> Terms -> Check -> SignUp -> Auth`, и собственно, за 5 итераций убежало 2 МБ. Понятно, что 2 МБ при нынешних ресурсах - это ничто, но там и на экранах по одному UILabel, и будь это что-то посерьезнее, то утечки бы исчислялись уже в десятках, а потом и сотнях мегабайт.

Так вот, вопрос, как вы с этим справляетесь? - я не имею ввиду процесс оптимизации работы с памятью (с Instruments->Allocations наперевес) :) я имею ввиду, что ссылки на UINavigationController'ы захватываются всеми, кому не попадя, например, при прокидывании последнего во вложенные координаторы (2го, 3го порядка, и т.д.). Т.е. _как правильно останавливать работу координатора, чтобы после этого не оставить нерелизнутые объекты_?

Спасибо!

**Comment by AndreyPanov** [comment]
Привет @remenkoff!
Большое спасибо за фидбэк 👍
По поводу вопросов:
1. Да, это сделано исключительно для примера, но такая ситуация возможна. Например мы в реальном приложении пытаемся загрузить список items, но наш dataProvider возвращает ошибку сессии (нужна повторная авторизация), в этом случае контроллер вызовет `authNeed`, чтобы координатор запустил флоу авторизации. Разумеется не во `viewDidAppear`, но все же.
2. Интересно, сейчас подебажил, действительно память течет. Казалось все правильно :) Исправлю и обновлю репу. 
Память в идеале должна так управляться: у нас есть роутер, он отвечает за контроллеры и если контроллер попнули - должен его зарелизить. При этом у роутера на `rootController` (почти всегда это `UINavigationController`) слабая ссылка. У координаторов есть `finishBlock`, который должен сконфигурить вызывающий его координатор и в нем вызвать 
```
coordinator.finishFlow = { [weak self, weak coordinator] in
            self?.router.dismissModule()
            self?.removeDependency(coordinator)
 } 
```

**Comment by AndreyPanov** [comment]
Хм, проверил, ликов в, описанном вами примере, не нашел. @remenkoff 
<img width="618" alt="screen shot 2017-03-07 at 16 12 58" src="https://cloud.githubusercontent.com/assets/783564/23662912/48856e86-0351-11e7-9929-3c40e4468183.png">
