### ISSUE TITLE
Coordinatable -> Coordinator

### ISSUE THREAD

**Issue by anatoliykant** [AndreyPanov/ApplicationCoordinator#16]
In Readme is written Coordin**atable**, the example Coordin**ator**:

protocol Coordinatable: class {
func start()
func start(with option: DeepLinkOption?)
}

correct  it if mistake.

**Comment by AndreyPanov** [comment]
@anatoliykant thank you. I am doing refactoring to make code more consistent and I'll also update Readme file.

**Comment by anatoliykant** [comment]
you are welcome
